"""initial migration

Revision ID: 02ecdf0cdb3e
Revises: 
Create Date: 2017-10-09 06:33:57.992068

"""
from alembic import op
import sqlalchemy as sa
from flaskbb.utils.database import UTCDateTime


# revision identifiers, used by Alembic.
revision = '02ecdf0cdb3e'
down_revision = None
branch_labels = (u'data_plugin',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rawdata',
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("thread_id", sa.Integer, nullable=False),
        sa.Column("thread_name", sa.String, nullable=False),
        sa.Column("post_num", sa.Integer, nullable=False),
        sa.Column("username", sa.String, nullable=False),
        sa.Column("message", sa.String, nullable=False),
        sa.Column("date_created", UTCDateTime(timezone=True), nullable=True ),
    )
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rawdata')
