"""add forum_id to table take 2

Revision ID: 256ff597a20c
Revises: 484532c61935
Create Date: 2017-10-10 14:18:01.900084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '256ff597a20c'
down_revision = '484532c61935'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thread_id', sa.Integer()))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_column('thread_id')
