"""add thread_id to topic

Revision ID: 484532c61935
Revises: fe62ea950c39
Create Date: 2017-10-10 14:11:06.023360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484532c61935'
down_revision = 'fe62ea950c39'
branch_labels = ()
depends_on = None


def upgrade():
    print('nothin')
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###


def downgrade():

    print('nothin')
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###
