"""add thread_id to topic

Revision ID: 484532c61935
Revises: fe62ea950c39
Create Date: 2017-10-10 14:11:06.023360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484532c61935'
down_revision = 'fe62ea950c39'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('hidden',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('rawdata', schema=None) as batch_op:
        batch_op.alter_column('date_created',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('forum_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.alter_column('hidden',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.alter_column('hidden',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('rawdata', schema=None) as batch_op:
        batch_op.alter_column('forum_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('date_created',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('hidden',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
