"""add forum_id to table

Revision ID: fe62ea950c39
Revises: 02ecdf0cdb3e
Create Date: 2017-10-10 12:07:11.496155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe62ea950c39'
down_revision = '02ecdf0cdb3e'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rawdata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forum_id', sa.Integer()))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rawdata', schema=None) as batch_op:
        batch_op.drop_column('forum_id')

    # ### end Alembic commands ###
